In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')

data cleaning

In [5]:
import os

In [13]:
dataset_path = r"C:\Users\harsh\OneDrive\Desktop\dataset"

images = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
            images.append([
                file,
                os.path.basename(root),
                os.path.join(root, file)
            ])

data = pd.DataFrame(images, columns=["filename", "class", "path"])

In [18]:
data

,filename,class,path
0,1.jpg,Accident,C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
1,10.jpg,Accident,C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
2,100.jpg,Accident,C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
3,1000.jpg,Accident,C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
4,1001.jpg,Accident,C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
...,...,...,...
12906,Traffic_Roads 5 (95).jpg,traffic road,C:\Users\harsh\OneDrive\Desktop\dataset\road\R...
12907,Traffic_Roads 5 (96).jpg,traffic road,C:\Users\harsh\OneDrive\Desktop\dataset\road\R...
12908,Traffic_Roads 5 (97).jpg,traffic road,C:\Users\harsh\OneDrive\Desktop\dataset\road\R...
12909,Traffic_Roads 5 (98).jpg,traffic road,C:\Users\harsh\OneDrive\Desktop\dataset\road\R...
12910,Traffic_Roads 5 (99).jpg,traffic road,C:\Users\harsh\OneDrive\Desktop\dataset\road\R...

In [16]:
data.head()

   filename     class                                               path
0     1.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
1    10.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
2   100.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
3  1000.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
4  1001.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12911 entries, 0 to 12910
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  12911 non-null  object
 1   class     12911 non-null  object
 2   path      12911 non-null  object
dtypes: object(3)
memory usage: 302.7+ KB

In [19]:
data.describe()

       filename     class                                               path
count     12911     12911                                              12911
unique    11941        13                                              12911
top       9.jpg  Accident  C:\Users\harsh\OneDrive\Desktop\dataset\Accide...
freq          4      6191                                                  1

In [20]:
data.isnull().sum()

filename    0
class       0
path        0
dtype: int64

corrupted image

In [21]:
from PIL import Image